### ISSUE TITLE
Exposing Directus part as standalone library

### ISSUE THREAD

**Issue by fluxxus** [jekuer/php-microsite-boilerplate#49]
Hi, I have one question, not really an issue or similar.

I see that you have Directus as an option in your boilerplate, and since my PHP skills are not up to the task I was wondering do you maybe have plans(or any pointers in the right direction for DIY approach) for exposing the Directus part of your boilerplate as standalone library?

Just by reading the code I can say that I get what is going on, but it's impossible for me to somehow extract only the Directus part and use it standalone.

Thanks

**Comment by jekuer** [comment]
Hi @fluxxus ,

Thanks for trying out my boilerplate project.
Unfortunately, there is no plan to create a wrapper just for the directus integration.
I would recommend to ping the directus team, whether they want to setup something within their examples repo.

Best,
Jens
