### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by djmtype** [jekuer/php-microsite-boilerplate#50]
@jekuer Thanks for providing this starter! 
I don't know if it's the PHP server I'm running, but I'm getting a bunch of these deprecated warnings: 
`Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Volumes/Evo/Sites/php-microsite-boilerplate/lib/gettext/gettext.inc on line 92`

I tried Docker, but it fails because I have an ARM Mac and the container doesn't support it even if I specify arm64 as a platform. 

I have not yet tried Valet. Just testing using this VS Code PHP server extension https://marketplace.visualstudio.com/items?itemName=Anuragsingk.anuragsingk-phpserver

**Comment by jekuer** [comment]
Should be fixed with latest patch
