### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by webgefaehrten** [jekuer/php-microsite-boilerplate#52]
Hello, unfortunately the routing on my vhost does not work, likewise on my other webspace it does not run. I proceeded exactly as described in the blog.

**Comment by jekuer** [comment]
Hi @TriXxer25 ,

Unfortunately, this message is to generic that it is impossible to say anything helpful regarding your issue.
Usually, routing is mainly driven by the webserver, which can be Apache or nginx in this case.
Check what you are running and whether your are using the right setup.

If this does not help, try to be way more precise with your description. What information would you, as a developer, need to debug something you have no clue about.

All the best,
Jens

**Comment by TriXxer25** [comment]
Hi @jekuer,
 
It's totally weird... The main page is loaded but the rest is not (imprint etc.). I'll have a look at the Apache settings until tomorrow and get back to you.

Thanks for the quick feedback.

Can we continue to speak in German? ;)

Many greetings

**Comment by TriXxer25** [comment]
Its working. Thanks a Lot. I was blind.

Thanks @jekuer
